# Generated by Django 5.1.5 on 2025-04-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки администратора'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='budget',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='source',
            field=models.CharField(blank=True, help_text='Страница, с которой была отправлена форма', max_length=200, null=True, verbose_name='Источник заявки'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='tariff',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User-Agent'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='website_honeypot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(max_length=17, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='service',
            field=models.CharField(choices=[('seo', 'SEO-продвижение'), ('email', 'Email-маркетинг'), ('content', 'Контент-маркетинг'), ('smm', 'SMM-продвижение'), ('orm', 'Репутационный маркетинг'), ('ppc', 'PPC-реклама'), ('complex', 'Комплексное продвижение'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
