# Generated by Django 5.1.5 on 2025-04-08 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_duplicate_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-идентификатор')),
            ],
            options={
                'verbose_name': 'Область экспертизы',
                'verbose_name_plural': 'Области экспертизы',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Компания')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Веб-сайт')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='Лет опыта')),
                ('expertise', models.ManyToManyField(blank=True, to='core.expertise', verbose_name='Области экспертизы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
