# Generated by Django 5.1.5 on 2025-04-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('services', '0003_delete_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='case_services', to='services.service', verbose_name='Связанные услуги'),
        ),
    ]
