# Generated by Django 5.1.5 on 2025-04-08 18:23

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Содержание'),
        ),
    ]
