# Generated by Django 5.1.5 on 2025-03-26 20:15

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-идентификатор')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('description', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('full_description', ckeditor.fields.RichTextField(verbose_name='Полное описание')),
                ('icon', models.CharField(blank=True, max_length=500, verbose_name='Иконка (класс или SVG)')),
                ('image', models.ImageField(blank=True, upload_to='services/', verbose_name='Изображение услуги')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, max_length=500, verbose_name='Meta Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Ответ')),
                ('is_common', models.BooleanField(default=False, help_text='Отметьте, если вопрос относится ко всем услугам', verbose_name='Общий вопрос')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-идентификатор')),
                ('description', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('full_description', ckeditor.fields.RichTextField(verbose_name='Полное описание')),
                ('image', models.ImageField(upload_to='cases/', verbose_name='Изображение кейса')),
                ('result', models.CharField(blank=True, max_length=200, verbose_name='Результат')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='Клиент')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Размещать на главной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('services', models.ManyToManyField(related_name='cases', to='services.service', verbose_name='Связанные услуги')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=500, verbose_name='Иконка (класс или SVG)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='services.service')),
            ],
            options={
                'verbose_name': 'Преимущество услуги',
                'verbose_name_plural': 'Преимущества услуг',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=500, verbose_name='Иконка (класс или SVG)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='services.service')),
            ],
            options={
                'verbose_name': 'Этап процесса',
                'verbose_name_plural': 'Этапы процесса',
                'ordering': ['order'],
            },
        ),
    ]
