# Generated by Django 5.1.5 on 2025-04-01 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Вставьте SVG-код иконки', verbose_name='SVG-иконка'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=True, verbose_name='Отображать на главной'),
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок пункта')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service')),
            ],
            options={
                'verbose_name': 'Особенность услуги',
                'verbose_name_plural': 'Особенности услуг',
                'ordering': ['service', 'order'],
            },
        ),
    ]
