# Generated by Django 5.1.5 on 2025-04-12 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='benefits_subtitle',
            field=models.TextField(blank=True, verbose_name='Подзаголовок секции "Преимущества"'),
        ),
        migrations.AddField(
            model_name='service',
            name='benefits_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок секции "Преимущества"'),
        ),
        migrations.AddField(
            model_name='service',
            name='cases_subtitle',
            field=models.TextField(blank=True, verbose_name='Подзаголовок секции "Кейсы"'),
        ),
        migrations.AddField(
            model_name='service',
            name='cases_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок секции "Кейсы"'),
        ),
        migrations.AddField(
            model_name='service',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email для связи'),
        ),
        migrations.AddField(
            model_name='service',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон для связи'),
        ),
        migrations.AddField(
            model_name='service',
            name='contact_subtitle',
            field=models.TextField(blank=True, verbose_name='Подзаголовок секции "Контакты"'),
        ),
        migrations.AddField(
            model_name='service',
            name='contact_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок секции "Контакты"'),
        ),
        migrations.AddField(
            model_name='service',
            name='explanation_subtitle',
            field=models.TextField(blank=True, verbose_name='Подзаголовок секции "Что такое"'),
        ),
        migrations.AddField(
            model_name='service',
            name='explanation_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок секции "Что такое"'),
        ),
        migrations.AddField(
            model_name='service',
            name='faq_subtitle',
            field=models.TextField(blank=True, verbose_name='Подзаголовок секции "FAQ"'),
        ),
        migrations.AddField(
            model_name='service',
            name='faq_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок секции "FAQ"'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_description',
            field=models.TextField(blank=True, verbose_name='Описание героической секции'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='services/hero/', verbose_name='Изображение героической секции'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок героической секции'),
        ),
        migrations.AddField(
            model_name='service',
            name='partners_subtitle',
            field=models.TextField(blank=True, verbose_name='Подзаголовок секции "Партнеры"'),
        ),
        migrations.AddField(
            model_name='service',
            name='partners_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок секции "Партнеры"'),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_subtitle',
            field=models.TextField(blank=True, verbose_name='Подзаголовок секции "Тарифы"'),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок секции "Тарифы"'),
        ),
        migrations.AddField(
            model_name='service',
            name='process_subtitle',
            field=models.TextField(blank=True, verbose_name='Подзаголовок секции "Как мы работаем"'),
        ),
        migrations.AddField(
            model_name='service',
            name='process_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок секции "Как мы работаем"'),
        ),
        migrations.AddField(
            model_name='service',
            name='services_subtitle',
            field=models.TextField(blank=True, verbose_name='Подзаголовок секции "Наши услуги"'),
        ),
        migrations.AddField(
            model_name='service',
            name='services_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок секции "Наши услуги"'),
        ),
        migrations.CreateModel(
            name='ServiceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='services/cases/', verbose_name='Изображение')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('result', models.CharField(max_length=100, verbose_name='Результат')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на подробности')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='services.service')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon_svg', models.TextField(blank=True, verbose_name='SVG-иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='services.service')),
            ],
            options={
                'verbose_name': 'Детальная услуга',
                'verbose_name_plural': 'Детальные услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDetailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст пункта')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.servicedetail')),
            ],
            options={
                'verbose_name': 'Пункт детальной услуги',
                'verbose_name_plural': 'Пункты детальных услуг',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon_svg', models.TextField(blank=True, verbose_name='SVG-иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='services.service')),
            ],
            options={
                'verbose_name': 'Блок объяснения',
                'verbose_name_plural': 'Блоки объяснений',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='services/partners/', verbose_name='Логотип')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('is_common', models.BooleanField(default=False, verbose_name='Общий партнер')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='services.service')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('period', models.CharField(default='в месяц', max_length=50, verbose_name='Период')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Краткое описание')),
                ('badge', models.CharField(blank=True, max_length=100, verbose_name='Бейдж (например, Рекомендуемый)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='services.service')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicePricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст функции')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.servicepricing')),
            ],
            options={
                'verbose_name': 'Функция тарифа',
                'verbose_name_plural': 'Функции тарифов',
                'ordering': ['order'],
            },
        ),
    ]
