# Generated by Django 5.1.5 on 2025-04-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_benefits_subtitle_service_benefits_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='service',
            name='full_description',
            field=models.TextField(verbose_name='Полное описание'),
        ),
    ]
