# Generated by Django 5.1.5 on 2025-04-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_icon_svg_service_is_featured_servicefeature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
    ]
