# Generated by Django 5.1.5 on 2025-04-08 18:38

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_delete_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=tinymce.models.HTMLField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='service',
            name='full_description',
            field=tinymce.models.HTMLField(verbose_name='Полное описание'),
        ),
    ]
